### PR TITLE
fix(koordlet):Unbind container level cfs_quota

### LINKED ISSUE #2633: [BUG]pod配置绑核后，所有容器会绑定相同的核，但容器的cpu limit变成-1
**What happened**:

Image

**What you expected to happen**:
pod绑定cpu时，cpu quota应该保持一样，否则会导致pod中单个容器把其它容器的cpu占用完，导致其它容器无cpu时间可用，出现假死情况

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- App version:
- Kubernetes version (use `kubectl version`):
- Install details (e.g. helm install args):
- Node environment (for koordlet/runtime-proxy issue):
  - Containerd/Docker version:
  - OS version:
  - Kernal version:
  - Cgroup driver: cgroupfs/systemd
- Others:

### PR DESCRIPTION
**Pull request by AutuSnow**
### Ⅰ. Describe what this PR does
This PR adds a new configuration option `--disable-unset-cpu-quota` to control whether container-level `cfs_quota` should be unset for cpuset pods (LSR/LSE QoS).
**Solution**:
- Add a new CLI flag `--disable-unset-cpu-quota` (default: `false`)
- When set to `true`, preserve container-level `cfs_quota` to enforce per-container CPU limits
- Containers rely on `cpu.shares` for fair CPU distribution when quota is unset
﻿
**Changes**:
- Add `RuntimeHookDisableUnsetCPUQuota` configuration field
### Ⅱ. Does this pull request fix one issue?
fixes #2633
### Ⅲ. Describe how to verify it
cd pkg/koordlet/runtimehooks/hooks/cpuset
go test -v -run TestUnsetPodCPUQuota
go test -v -run TestUnsetContainerCPUQuota
---

### CODE REVIEW

File: pkg/koordlet/runtimehooks/hooks/cpuset/cpuset_test.go [hunk 1]
```diff
@@ -591,6 +646,84 @@ func TestUnsetContainerCPUQuota(t *testing.T) {
...
+						CgroupParent: "kubepods/test-pod/test-container/",
+					},
+				},
+				disableUnsetCPUQuota: true,
+			},
+			wantErr:      false,
+			wantCPUQuota: nil,
+		},
+		{
+			name: "reproduce issue: container without quota limit can starve other containers",
```
Comment (saintube) [inline pkg/koordlet/runtimehooks/hooks/cpuset/cpuset_test.go]:
```suggestion
			name: "unset container cfs_quota by design",
```

This behavior is expected for some cases, e.g. the cfs_quota_us can throttle the cpuset pod even when the pod's cpu request are equal to the cpu limit.

Same below.

Comment (AutuSnow) [reply pkg/koordlet/runtimehooks/hooks/cpuset/cpuset_test.go]: Thanks for the feedback! You're right that the current behavior is by design
This PR doesn't treat the current behavior as a bug, but provides an alternative
option for users who prioritize preventing CPU starvation over avoiding throttle.
﻿
I'll update the test case naming to be more neutral:
- "default behavior: unset cfs_quota to avoid throttle"
- "alternative behavior: preserve cfs_quota to prevent CPU starvation"
﻿
Both behaviors have trade-offs:
- Unset quota: Avoids throttle but may cause starvation
- Keep quota: Prevents starvation but may cause throttle

Comment (saintube) [reply pkg/koordlet/runtimehooks/hooks/cpuset/cpuset_test.go]: yep

**Comment by saintube** [comment]
@AutuSnow Before merging this PR, please sign off your commit to pass the DCO check: https://github.com/koordinator-sh/koordinator/pull/2767/checks?check_run_id=59692070292

File: pkg/scheduler/plugins/elasticquota/hook_plugin_test.go [hunk 2]
```diff
@@ -192,6 +192,9 @@ func TestUpdateQuota_IsQuotaUpdated(t *testing.T) {
 		assert.NotNil(t, newQuotaInfo, "newQuotaInfo should not be nil")
 		assert.NotNil(t, quota, "quota should not be nil")
 		assert.NotNil(t, state, "state should not be nil")
+		if quota.Name != q1Modified.Name {
```
Comment (saintube) [inline pkg/scheduler/plugins/elasticquota/hook_plugin_test.go:195]: What does this fix?

Comment (AutuSnow) [reply pkg/scheduler/plugins/elasticquota/hook_plugin_test.go:195]: I remember that it was modified when CI reported an error
fix race condition in TestUpdateQuota_IsQuotaUpdated

Comment (saintube) [reply pkg/scheduler/plugins/elasticquota/hook_plugin_test.go:195]: Could you please add the link of the CI failure to fix?

Comment (AutuSnow) [reply pkg/scheduler/plugins/elasticquota/hook_plugin_test.go:195]: Oh my god, I shouldn't be able to find this

Comment (AutuSnow) [reply pkg/scheduler/plugins/elasticquota/hook_plugin_test.go:195]: https://github.com/koordinator-sh/koordinator/actions/runs/20857233715/job/59927115065

**Comment by saintube** [comment]
@AutuSnow https://github.com/koordinator-sh/koordinator/pull/2767#discussion_r2672085645 this comment is still unresolved

**Comment by AutuSnow** [comment]
@saintube According to my reply, doesn't it need to be modified?

**Comment by saintube** [comment]
> @saintube According to my reply, doesn't it need to be modified?

Have you updated the test case naming as above?

**Comment by AutuSnow** [comment]
I have revised the unit test name

File: docs/proposals/scheduling/gpu-asymmetric-allocation.md [hunk 3]
```diff
@@ -0,0 +1,2471 @@
+# GPU 非对称分配和碎片整理设计方案
```
Comment (saintube) [inline docs/proposals/scheduling/gpu-asymmetric-allocation.md]: This file should not be included in this PR

Comment (AutuSnow) [reply docs/proposals/scheduling/gpu-asymmetric-allocation.md]: Changed

**Review by saintube — APPROVED** [review]
/lgtm
