### PR TITLE
scheduler: revise reservation metrics

### LINKED ISSUE #2813: [Flaking tests]Test_allocateWithNominated/reservation-ignored_pod panic with nil pointer dereference
### Description
﻿
`Test_allocateWithNominated/reservation-ignored_pod` in `pkg/scheduler/plugins/deviceshare/reservation_test.go` panics with a nil pointer dereference at `devicehandler_gpu.go:41`.
﻿
This test case was introduced in commit `72af3153` (PR #2752: scheduler: deviceshare adapt pre-allocation) on 2026-01-06.
﻿
### Steps to Reproduce
﻿
go test ./pkg/scheduler/plugins/deviceshare/... -run "Test_allocateWithNominated/reservation-ignored_pod" -v
﻿
Panic Stack Trace
﻿
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x30f54ed]
﻿
Failed Ci :https://github.com/koordinator-sh/koordinator/actions/runs/22379282089/job/64776244495?pr=2799
﻿
Root Cause
﻿
In the reservation-ignored pod test case, allocateWithNominated calls tryAllocateIgnoreReservation, which calls allocator.Allocate() → Prepare() → calcRequestsAndCountByDeviceType() → GPUHandler.CalcDesiredRequestsAndCount(). At devicehandler_gpu.go:41, it accesses nodeDevice.deviceTotal[schedulingv1alpha1.GPU] but nodeDevice is nil, causing the panic.

### PR DESCRIPTION
**Pull request by saintube**
### Ⅰ. Describe what this PR does

koord-scheduler:
1. Enhance the metrics `scheduler_reservation_status_phase` by transitioning from incomplete, event-triggered recording to periodic refreshes for all cluster-wide reservations.
2. Fix the flaky test `Test_allocateWithNominated `.

### Ⅱ. Does this pull request fix one issue?

fixes #2813

### V. Checklist

- [x] I have written necessary docs and comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `make test`

### CODE REVIEW

**Comment by googs1025** [comment]
will help to review this this week

File: pkg/scheduler/plugins/reservation/controller/controller.go [hunk 1]
```diff
@@ -410,6 +420,23 @@ func nextSyncTime(r *schedulingv1alpha1.Reservation) time.Duration {
...
+	if err != nil {
+		klog.Errorf("failed to list reservations, abort the resync turn, err: %s", err)
+		return
+	}
+	metrics.ResetReservationPhase()
+	for _, reservation := range reservations {
+		// record metrics
+		RecordReservationPhases(reservation)
+	}
+}
```
Comment (googs1025) [inline pkg/scheduler/plugins/reservation/controller/controller.go:439]: can we add debug log here? This could be more helpful for debug.

`klog.V(4).InfoS("resynced reservation metrics", "count", len(reservations))`

File: pkg/scheduler/plugins/reservation/controller/controller.go [hunk 2]
```diff
@@ -410,6 +420,23 @@ func nextSyncTime(r *schedulingv1alpha1.Reservation) time.Duration {
...
+	reservations, err := c.reservationLister.List(labels.Everything())
+	if err != nil {
+		klog.Errorf("failed to list reservations, abort the resync turn, err: %s", err)
+		return
+	}
+	metrics.ResetReservationPhase()
+	for _, reservation := range reservations {
+		// record metrics
+		RecordReservationPhases(reservation)
+	}
```
Comment (googs1025) [inline pkg/scheduler/plugins/reservation/controller/controller.go:437]: This seem not to be an atomic. I'm unsure if this will be some problems for monitoring, such as false alarms (all reservations disappear?).

Comment (saintube) [reply pkg/scheduler/plugins/reservation/controller/controller.go:437]: I suppose it is acceptable since the metric recording is very fast, thus only little chance overlapped with Prometheus scrape cycles. And the infrequent non-atomic updates are generally tolerable for monitoring.

**Comment by saintube** [comment]
PTAL /cc @googs1025
