### PR TITLE
koordlet: fix for cpu suppress when node topology reporting disabled

### LINKED ISSUE #730: [BUG] koordlet UT failed when reporting topology
**What happened**:

```log
I1021 02:43:37.222645   51011 states_noderesourcetopology.go:229] start to report node topology
==================
WARNING: DATA RACE
Read at 0x0000050c869a by goroutine 79:
  k8s.io/klog/v2.(*loggingT).header()
      /home/runner/go/pkg/mod/k8s.io/klog/v2@v2.10.0/klog.go:607 +0xc5
  k8s.io/klog/v2.(*loggingT).printf()
      /home/runner/go/pkg/mod/k8s.io/klog/v2@v2.10.0/klog.go:739 +0x84
  k8s.io/klog/v2.Infof()
      /home/runner/go/pkg/mod/k8s.io/klog/v2@v2.10.0/klog.go:1408 +0x34b
  github.com/koordinator-sh/koordinator/pkg/koordlet/statesinformer.(*callbackRunner).Start.func1()
      /home/runner/work/koordinator/koordinator/pkg/koordlet/statesinformer/callback_runner.go:138 +0x25b

Previous write at 0x0000050c869a by goroutine 20:
  flag.newBoolValue()
      /opt/hostedtoolcache/go/1.17.13/x64/src/flag/flag.go:[112](https://github.com/koordinator-sh/koordinator/actions/runs/3294352738/jobs/5431778821#step:11:113) +0x2fb
  flag.(*FlagSet).BoolVar()
      /opt/hostedtoolcache/go/1.17.13/x64/src/flag/flag.go:632 +0x307
  k8s.io/klog/v2.InitFlags()
      /home/runner/go/pkg/mod/k8s.io/klog/v2@v2.10.0/klog.go:437 +0x2d6
  k8s.io/component-base/logs.UnsupportedLoggingFlags()
      /home/runner/go/pkg/mod/k8s.io/component-base@v0.22.6/logs/config.go:71 +0x7c
  k8s.io/component-base/logs.BindLoggingFlags()
      /home/runner/go/pkg/mod/k8s.io/component-base@v0.22.6/logs/config.go:56 +0x70
  k8s.io/kubernetes/cmd/kubelet/app/options.AddKubeletConfigFlags()
      /home/runner/go/pkg/mod/k8s.io/kubernetes@v1.22.6/cmd/kubelet/app/options/options.go:547 +0x292b
  github.com/koordinator-sh/koordinator/pkg/util/kubelet.NewKubeletOptions()
      /home/runner/work/koordinator/koordinator/pkg/util/kubelet/kubelet.go:63 +0x215
  github.com/koordinator-sh/koordinator/pkg/koordlet/statesinformer.(*nodeTopoInformer).reportNodeTopology()
      /home/runner/work/koordinator/koordinator/pkg/koordlet/statesinformer/states_noderesourcetopology.go:246 +0x554
  github.com/koordinator-sh/koordinator/pkg/koordlet/statesinformer.Test_reportNodeTopology()
      /home/runner/work/koordinator/koordinator/pkg/koordlet/statesinformer/states_noderesourcetopology_test.go:319 +0x11d1
  testing.tRunner()
      /opt/hostedtoolcache/go/1.17.13/x64/src/testing/testing.go:1259 +0x22f
  testing.(*T).Run·dwrap·21()
      /opt/hostedtoolcache/go/1.17.13/x64/src/testing/testing.go:1306 +0x47

Goroutine 79 (running) created at:
  github.com/koordinator-sh/koordinator/pkg/koordlet/statesinformer.(*callbackRunner).Start()
      /home/runner/work/koordinator/koordinator/pkg/koordlet/statesinformer/callback_runner.go:127 +0xad
  github.com/koordinator-sh/koordinator/pkg/koordlet/statesinformer.(*statesInformer).Run·dwrap·5()
      /home/runner/work/koordinator/koordinator/pkg/koordlet/statesinformer/states_informer.go:136 +0x47

Goroutine 20 (running) created at:
  testing.(*T).Run()
      /opt/hostedtoolcache/go/1.17.13/x64/src/testing/testing.go:1306 +0x726
  testing.runTests.func1()
      /opt/hostedtoolcache/go/1.17.13/x64/src/testing/testing.go:1598 +0x99
  testing.tRunner()
      /opt/hostedtoolcache/go/1.17.13/x64/src/testing/testing.go:1259 +0x22f
  testing.runTests()
      /opt/hostedtoolcache/go/1.17.13/x64/src/testing/testing.go:1596 +0x7ca
  testing.(*M).Run()
      /opt/hostedtoolcache/go/1.17.13/x64/src/testing/testing.go:1504 +0x9d1
  main.main()
      _testmain.go:161 +0x324
  runtime.main()
      /opt/hostedtoolcache/go/1.17.13/x64/src/runtime/proc.go:255 +0x226
  github.com/cilium/ebpf/link.init()
      /home/runner/go/pkg/mod/github.com/cilium/ebpf@v0.6.2/link/syscalls.go:50 +0x2a8
  github.com/cilium/ebpf/link.init()
      /home/runner/go/pkg/mod/github.com/cilium/ebpf@v0.6.2/link/syscalls.go:29 +0x24a
  runtime.doInit()
      /opt/hostedtoolcache/go/1.17.13/x64/src/runtime/proc.go:6498 +0x122
  github.com/cilium/ebpf.init()
      /home/runner/go/pkg/mod/github.com/cilium/ebpf@v0.6.2/syscalls.go:426 +0x690
  github.com/cilium/ebpf.init()
      /home/runner/go/pkg/mod/github.com/cilium/ebpf@v0.6.2/prog.go:458 +0x630
  github.com/cilium/ebpf.init()
      /home/runner/go/pkg/mod/github.com/cilium/ebpf@v0.6.2/syscalls.go:408 +0x5d0
  github.com/cilium/ebpf.init()
      /home/runner/go/pkg/mod/github.com/cilium/ebpf@v0.6.2/syscalls.go:236 +0x570
  github.com/cilium/ebpf.init()
      /home/runner/go/pkg/mod/github.com/cilium/ebpf@v0.6.2/syscalls.go:220 +0x510
  github.com/cilium/ebpf.init()
      /home/runner/go/pkg/mod/github.com/cilium/ebpf@v0.6.2/syscalls.go:203 +0x4b0
  github.com/cilium/ebpf.init()
      /home/runner/go/pkg/mod/github.com/cilium/ebpf@v0.6.2/syscalls.go:185 +0x44e
  runtime.doInit()
      /opt/hostedtoolcache/go/1.17.13/x64/src/runtime/proc.go:6498 +0x122
  github.com/cilium/ebpf/internal/btf.init()
      /home/runner/go/pkg/mod/github.com/cilium/ebpf@v0.6.2/internal/btf/btf.go:728 +0x1bc
==================
==================
WARNING: DATA RACE
Read at 0x0000050c8698 by goroutine 79:
  k8s.io/klog/v2.(*loggingT).formatHeader()
      /home/runner/go/pkg/mod/k8s.io/klog/v2@v2.10.0/klog.go:627 +0xdd
  k8s.io/klog/v2.(*loggingT).header()
      /home/runner/go/pkg/mod/k8s.io/klog/v2@v2.10.0/klog.go:614 +0x199
  k8s.io/klog/v2.(*loggingT).printf()
      /home/runner/go/pkg/mod/k8s.io/klog/v2@v2.10.0/klog.go:739 +0x84
  k8s.io/klog/v2.Infof()
      /home/runner/go/pkg/mod/k8s.io/klog/v2@v2.10.0/klog.go:1408 +0x34b
  github.com/koordinator-sh/koordinator/pkg/koordlet/statesinformer.(*callbackRunner).Start.func1()
      /home/runner/work/koordinator/koordinator/pkg/koordlet/statesinformer/callback_runner.go:138 +0x25b

Previous write at 0x0000050c8698 by goroutine 20:
  flag.newBoolValue()
      /opt/hostedtoolcache/go/1.17.13/x64/src/flag/flag.go:112 +0x35b
  flag.(*FlagSet).BoolVar()
      /opt/hostedtoolcache/go/1.17.13/x64/src/flag/flag.go:632 +0x367
  k8s.io/klog/v2.InitFlags()
      /home/runner/go/pkg/mod/k8s.io/klog/v2@v2.10.0/klog.go:438 +0x338
  k8s.io/component-base/logs.UnsupportedLoggingFlags()
      /home/runner/go/pkg/mod/k8s.io/component-base@v0.22.6/logs/config.go:71 +0x7c
  k8s.io/component-base/logs.BindLoggingFlags()
      /home/runner/go/pkg/mod/k8s.io/component-base@v0.22.6/logs/config.go:56 +0x70
  k8s.io/kubernetes/cmd/kubelet/app/options.AddKubeletConfigFlags()
      /home/runner/go/pkg/mod/k8s.io/kubernetes@v1.22.6/cmd/kubelet/app/options/options.go:547 +0x292b
  github.com/koordinator-sh/koordinator/pkg/util/kubelet.NewKubeletOptions()
      /home/runner/work/koordinator/koordinator/pkg/util/kubelet/kubelet.go:63 +0x215
  github.com/koordinator-sh/koordinator/pkg/koordlet/statesinformer.(*nodeTopoInformer).reportNodeTopology()
      /home/runner/work/koordinator/koordinator/pkg/koordlet/statesinformer/states_noderesourcetopology.go:246 +0x554
  github.com/koordinator-sh/koordinator/pkg/koordlet/statesinformer.Test_reportNodeTopology()
      /home/runner/work/koordinator/koordinator/pkg/koordlet/statesinformer/states_noderesourcetopology_test.go:319 +0x11d1
  testing.tRunner()
      /opt/hostedtoolcache/go/1.17.13/x64/src/testing/testing.go:1259 +0x22f
  testing.(*T).Run·dwrap·21()
      /opt/hostedtoolcache/go/1.17.13/x64/src/testing/testing.go:1306 +0x47

Goroutine 79 (running) created at:
  github.com/koordinator-sh/koordinator/pkg/koordlet/statesinformer.(*callbackRunner).Start()
      /home/runner/work/koordinator/koordinator/pkg/koordlet/statesinformer/callback_runner.go:127 +0xad
  github.com/koordinator-sh/koordinator/pkg/koordlet/statesinformer.(*statesInformer).Run·dwrap·5()
      /home/runner/work/koordinator/koordinator/pkg/koordlet/statesinformer/states_informer.go:136 +0x47

Goroutine 20 (running) created at:
  testing.(*T).Run()
      /opt/hostedtoolcache/go/1.17.13/x64/src/testing/testing.go:1306 +0x726
  testing.runTests.func1()
      /opt/hostedtoolcache/go/1.17.13/x64/src/testing/testing.go:1598 +0x99
  testing.tRunner()
      /opt/hostedtoolcache/go/1.17.13/x64/src/testing/testing.go:1259 +0x22f
  testing.runTests()
      /opt/hostedtoolcache/go/1.17.13/x64/src/testing/testing.go:1596 +0x7ca
  testing.(*M).Run()
      /opt/hostedtoolcache/go/1.17.13/x64/src/testing/testing.go:1504 +0x9d1
  main.main()
      _testmain.go:161 +0x324
  runtime.main()
      /opt/hostedtoolcache/go/1.17.13/x64/src/runtime/proc.go:255 +0x226
  github.com/cilium/ebpf/link.init()
      /home/runner/go/pkg/mod/github.com/cilium/ebpf@v0.6.2/link/syscalls.go:50 +0x2a8
  github.com/cilium/ebpf/link.init()
      /home/runner/go/pkg/mod/github.com/cilium/ebpf@v0.6.2/link/syscalls.go:29 +0x24a
  runtime.doInit()
      /opt/hostedtoolcache/go/1.17.13/x64/src/runtime/proc.go:6498 +0x122
  github.com/cilium/ebpf.init()
      /home/runner/go/pkg/mod/github.com/cilium/ebpf@v0.6.2/syscalls.go:426 +0x690
  github.com/cilium/ebpf.init()
      /home/runner/go/pkg/mod/github.com/cilium/ebpf@v0.6.2/prog.go:458 +0x630
  github.com/cilium/ebpf.init()
      /home/runner/go/pkg/mod/github.com/cilium/ebpf@v0.6.2/syscalls.go:408 +0x5d0
  github.com/cilium/ebpf.init()
      /home/runner/go/pkg/mod/github.com/cilium/ebpf@v0.6.2/syscalls.go:236 +0x570
  github.com/cilium/ebpf.init()
      /home/runner/go/pkg/mod/github.com/cilium/ebpf@v0.6.2/syscalls.go:220 +0x510
  github.com/cilium/ebpf.init()
      /home/runner/go/pkg/mod/github.com/cilium/ebpf@v0.6.2/syscalls.go:203 +0x4b0
  github.com/cilium/ebpf.init()
      /home/runner/go/pkg/mod/github.com/cilium/ebpf@v0.6.2/syscalls.go:185 +0x44e
  runtime.doInit()
      /opt/hostedtoolcache/go/1.17.13/x64/src/runtime/proc.go:6498 +0x122
  github.com/cilium/ebpf/internal/btf.init()
      /home/runner/go/pkg/mod/github.com/cilium/ebpf@v0.6.2/internal/btf/btf.go:728 +0x1bc
==================
I1021 02:43:37.225547   51011 callback_runner.go:138] callback runner RegisterTypeNodeSLOSpec loop is exited
I1021 02:43:37.225929   51011 callback_runner.go:138] callback runner RegisterTypeAllPods loop is exited
I1021 02:43:37.225978   51011 callback_runner.go:138] callback runner RegisterTypeNodeTopology loop is exited
--- FAIL: Test_reportNodeTopology (0.00s)
    testing.go:[115](https://github.com/koordinator-sh/koordinator/actions/runs/3294352738/jobs/5431778821#step:11:116)2: race detected during execution of test
```

**What you expected to happen**:

UT passed

**How to reproduce it (as minimally and precisely as possible)**:

Run UT `Test_reportNodeTopology`

**Anything else we need to know?**:

**Environment**:
- App version:
- Kubernetes version (use `kubectl version`):
- Install details (e.g. helm install args):
- Node environment (for koordlet/runtime-proxy issue):
  - Containerd/Docker version:
  - OS version:
  - Kernal version:
  - Cgroup driver: cgroupfs/systemd
- Others:

### PR DESCRIPTION
**Pull request by saintube**
Signed-off-by: saintube <saintube@foxmail.com>

### Ⅰ. Describe what this PR does

Fix for CPU Suppress when koordlet disables *NodeTopologyReport*.

### Ⅱ. Does this pull request fix one issue?

With this patch, nodeResourceTopology will be updated internally even if we set `NodeTopologyReport=false` in the feature-gates. It works when we want to enable CPU Suppress but disable NodeTopologyReport.

May also fixes #730 .

### Ⅲ. Describe how to verify it

1. Deploy koordinator.
2. Set `BECPUSuppress=true,NodeTopologyReport=false` in the koordlet's feature-gates.
3. Check if CPU Suppress works well.

### V. Checklist

- [X] I have written necessary docs and comments
- [X] I have added necessary unit tests and integration tests
- [X] All checks passed in `make test`

### CODE REVIEW

File: pkg/koordlet/statesinformer/states_noderesourcetopology.go [hunk 1]
```diff
@@ -227,113 +309,51 @@ func (s *nodeTopoInformer) calGuaranteedCpu(usedCPUs map[int32]*extension.CPUInf
...
+		if features.DefaultKoordletFeatureGate.Enabled(features.NodeTopologyReport) {
+			nodeResourceTopology, err = s.topologyClient.TopologyV1alpha1().NodeResourceTopologies().Get(ctx, node.Name, metav1.GetOptions{ResourceVersion: "0"})
 			if err != nil {
-				klog.Errorf("failed to marshal pod allocs, err: %v", err)
-				return
+				klog.Errorf("failed to get node resource topology %s, err: %v", node.Name, err)
+				return err
 			}
+		} else {
+			nodeResourceTopology = &v1alpha1.NodeResourceTopology{}
```
Comment (zwzhang0107) [inline pkg/koordlet/statesinformer/states_noderesourcetopology.go:337]: define func newNodeTopo() with nodeName like L127
return &v1alpha1.NodeResourceTopology{
xxxx
}
