### PR TITLE
bugfix: fix exec exit with 126

### LINKED ISSUE #437: [BUG]koord-runtime-proxy failed to proxy exec request without -it option
**What happened**:
Any scenario involving with exec request, including `ExecSync` for docker, `PostStartHook` for pod Lifecycle, and readiness probe etc., the exec will be failed as shown below.
image

**What you expected to happen**:
They should be executed successfully.

**How to reproduce it (as minimally and precisely as possible)**:
It is very easy to reproduce. As long as echo something when exec. For example, the following pod manifest has a `postStart` hook and `echo 1` . It will fail to start pods and the error is the screenshot from the above.
```
apiVersion: v1
kind: Pod
metadata:
  name: sample
spec:
  containers:
  - env:
    - name: TEST
      value: value0
    image: nginx:1.20.1-alpine
    lifecycle:
      postStart:
        exec:
          command:
          - /bin/sh
          - -c
          - echo 1 && sleep 2s
    name: main
    readinessProbe:
      failureThreshold: 3
      periodSeconds: 10
      successThreshold: 1
      tcpSocket:
        port: 80
      timeoutSeconds: 1
```

**Anything else we need to know?**:
We found a very interesting fact: 
When try to manually trigger it using docker cli
```
docker --host=unix:///var/run/runtimeproxy/runtimeproxy.sock exec -it 246ab5790f80 /bin/sh -c "echo 1 && sleep 2s"
```
Everything is doing well. However, when remove `-it` flag 
```
docker --host=unix:///var/run/runtimeproxy/runtimeproxy.sock exec 246ab5790f80 /bin/sh -c "echo 1 && sleep 2s"
```
The error reproduced.
It turns out that, kubelet will set `in` to `nil` and `tty` to `false` when doing `exec`. 
image

And koord-runtime-proxy only proxies `exec` request without intercepting. We highly doubt the problem is the reverse proxy.
image

**Environment**:
- Kubernetes version (use `kubectl version`): v1.18

### PR DESCRIPTION
**Pull request by ZYecho**
Signed-off-by: Yue Zhang <huaihuan.zy@alibaba-inc.com>

### Ⅰ. Describe what this PR does
fix #437 

### V. Checklist

- [ ] I have written necessary docs and comments
- [ ] I have added necessary unit tests and integration tests
- [ ] All checks passed in `make test`

### CODE REVIEW

File: pkg/util/httputil/reverseproxy.go [hunk 1]
```diff
@@ -0,0 +1,650 @@
+/*
+Copyright 2022 The Koordinator Authors.
+
```
Comment (hormes) [inline pkg/util/httputil/reverseproxy.go:3]: should add the original license here
