### PR TITLE
koord-manager: improve batch resource calculation with system metrics

### LINKED ISSUE #1427: [BUG] SLO-Controller calculation batch-cpu fluctuates frequently
**What happened**:

The BE Resource is calculated by the formula ```Node.Total - Node.Reserved - System.Used - Pod(non-BE).Used```, where ```System.Used = Node.Used - Pod(All).Used```. However, the System.Used calculation implementation has some problems, as follows: 
* At time t1, NodeMetric is updated; at time t2, the controller calculates NodeResource based on the update of NodeMetric. 
* Pod-B ends at time t2, and the controller regards the usage of Pod-B as System.Used

| component  | t1 | t2 | t3 | 
| ------------- | ------------- | ------------- | ------------- |
| koordlet  | node usage：2.5 core <br/> BE Pod-A: 1 core <br/> BE Pod-B: 1 core <br/> update NodeMetrics  | node usage：1.5 core <br/> BE Pod-A: 1 core <br/> BE Pod-B: terminated <br/> update NodeMetrics |
| slo-controller  | | node usage：2.5 core <br/> BE Pod-A: 1 core <br/> BE Pod-B: terminated <br/> calculate node resource | node usage：1.5 core <br/> BE Pod-A: 1 core <br/> BE Pod-B: terminated <br/> calculate node resource |

Calculated according to the code of https://github.com/koordinator-sh/koordinator/blob/v1.2.0/pkg/slo-controller/noderesource/plugins/batchresource/plugin.go#L82

| t1 | t2 | t3 | 
| ------------- | ------------- | ------------- |
| System.Used：0.5 core <br/> Batch-CPU: x core |  System.Used：1.5 core <br/> Batch-CPU: x-1 core  | System.Used：0.5 core <br/> Batch-CPU: x core |

**What you expected to happen**:

Expecting time t2, the controller calculates System.Used = 0.5 core

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

Node.Used uses the average value of the last 60 seconds, and Pod(All).Used uses the current value, which also causes the System.Used value to be inaccurate.

### PR DESCRIPTION
**Pull request by saintube**
### Ⅰ. Describe what this PR does

koord-manager: Improve the calculation of the batch resource allocatable with the newly-added system metrics.

### Ⅱ. Does this pull request fix one issue?

Fixes #1427.

### Ⅳ. Special notes for reviews

Please note that the calculated allocatable can be lower than the real result at the nodeMetric reported time. It becomes accurate when there are no more pods terminated or newly-scheduled between the nodeMetric reported time and the controller calculating time.

### V. Checklist

- [ ] I have written necessary docs and comments
- [ ] I have added necessary unit tests and integration tests
- [ ] All checks passed in `make test`

### CODE REVIEW

File: pkg/slo-controller/noderesource/plugins/batchresource/plugin.go [hunk 1]
```diff
@@ -113,36 +119,47 @@ func (p *Plugin) Calculate(strategy *configuration.ColocationStrategy, node *cor
 			continue
 		}
 
+		// mark listed pod metric
+		podKey := util.GetPodKey(pod)
+		podMetric, hasMetric := podMetricMap[podKey]
```
Comment (zwzhang0107) [inline pkg/slo-controller/noderesource/plugins/batchresource/plugin.go:124]: define another map to mark whether the podMetric has been added

File: pkg/slo-controller/noderesource/plugins/batchresource/plugin.go [hunk 2]
```diff
@@ -96,10 +101,11 @@ func (p *Plugin) Calculate(strategy *configuration.ColocationStrategy, node *cor
 
 	// compute the requests and usages according to the pods' priority classes.
 	// HP means High-Priority (i.e. not Batch or Free) pods
-	// pod(HP).Used = pod(All).Used - pod(Batch/Free).Used
-	podAllUsed := util.NewZeroResourceList()
 	podHPRequest := util.NewZeroResourceList()
 	podHPUsed := util.NewZeroResourceList()
+	// podMissingUsed denotes the sum usage of pods which is reported in NodeMetric but not listed currently.
+	// It could be regarded as the HP part.
+	podMissingUsed := util.NewZeroResourceList()
```
Comment (zwzhang0107) [inline pkg/slo-controller/noderesource/plugins/batchresource/plugin.go:108]: danglingPod/unknownPriorityPod

File: pkg/slo-controller/noderesource/plugins/batchresource/plugin.go [hunk 3]
```diff
@@ -113,36 +119,47 @@ func (p *Plugin) Calculate(strategy *configuration.ColocationStrategy, node *cor
...
+	for podKey, podMetric := range podMetricMap {
+		if podMetric == nil { // pod is in the current pod list
+			continue
 		}
-		podAllUsed = quotav1.Add(podAllUsed, getPodMetricUsage(podMetric))
+		podMissingUsed = quotav1.Add(podMissingUsed, getPodMetricUsage(podMetric))
+		hasMissingPod = true
+		klog.V(6).InfoS("batch resource got missing pods", "node", node.Name, "pod", podKey)
+	}
+	if hasMissingPod {
```
Comment (zwzhang0107) [inline pkg/slo-controller/noderesource/plugins/batchresource/plugin.go:152]: hasMissingPod seems not necessary since podMissingUsed will be zero if hasMissingPod is false

File: pkg/slo-controller/noderesource/plugins/batchresource/plugin.go (hunk 1 above)
Comment (saintube) [reply pkg/slo-controller/noderesource/plugins/batchresource/plugin.go:126]: no longer change the map, use the subtraction between all pods' used and shown pods's used

File: pkg/slo-controller/noderesource/plugins/batchresource/plugin.go (hunk 2 above)
Comment (saintube) [reply pkg/slo-controller/noderesource/plugins/batchresource/plugin.go]: fixed

File: pkg/slo-controller/noderesource/plugins/batchresource/plugin.go (hunk 3 above)
Comment (saintube) [reply pkg/slo-controller/noderesource/plugins/batchresource/plugin.go]: this check was just for logging. now always log the dangling used with v=6

File: pkg/slo-controller/noderesource/plugins/batchresource/plugin.go [hunk 4]
```diff
@@ -113,36 +121,39 @@ func (p *Plugin) Calculate(strategy *configuration.ColocationStrategy, node *cor
...
+		if !isPodHighPriority {
 			continue
 		}
-
-		if isPodHighPriority {
+		podHPRequest = quotav1.Add(podHPRequest, podRequest)
+		if hasMetric {
 			podHPUsed = quotav1.Add(podHPUsed, getPodMetricUsage(podMetric))
+		} else {
+			podHPUsed = quotav1.Add(podHPUsed, podRequest)
```
Comment (j4ckstraw) [inline pkg/slo-controller/noderesource/plugins/batchresource/plugin.go:142]: why use Request if hos no metric, how about skip?
