### PR TITLE
koord-scheduler: fix deletion of Reservation in concurrent scenarios

### LINKED ISSUE #1436: [BUG] after delete reservation, failed to schedule pod with "nodeinfo not found for node name"
**What happened**:

1. Create reservation and assigned by scheduler to one node A.
2. Delete the assigned reservation.
3. Create new Pod
4. Got error `nodeinfo not found for node name "nodeA"`

**What you expected to happen**:

Successfully assigned the new Pod.

**How to reproduce it (as minimally and precisely as possible)**:

Cannot reproduce.

**Anything else we need to know?**:

**Environment**:
- App version:
- Kubernetes version (use `kubectl version`):
- Install details (e.g. helm install args):
- Node environment (for koordlet/runtime-proxy issue):
  - Containerd/Docker version:
  - OS version:
  - Kernal version:
  - Cgroup driver: cgroupfs/systemd
- Others:

### PR DESCRIPTION
**Pull request by eahydra**
### Ⅰ. Describe what this PR does

Fix deletion of Reservation in concurrent scenarios. 
When deleting one Reservation, maybe the event handler of plugin `Reservation` got event after the `deleteReservationFromSchedulerCache` in `pkg/scheduler/frameworkext/eventhandlers`, so the deleted ReservationInfo re-added into the ReservationCache.
And optimize the log about reservation to help diagnose.

### Ⅱ. Does this pull request fix one issue?

fix #1436

### V. Checklist

- [x] I have written necessary docs and comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `make test`

### CODE REVIEW

**Review by FillZpp — APPROVED** [review]
/lgtm

File: pkg/scheduler/plugins/reservation/eventhandler.go [hunk 1]
```diff
@@ -91,6 +91,6 @@ func (h *reservationEventHandler) OnDelete(obj interface{}) {
 		r = r.DeepCopy()
 		r.Status.Phase = schedulingv1alpha1.ReservationFailed
 	}
-	h.cache.updateReservation(r)
-	klog.V(5).InfoS("reservation cache delete", "reservation", klog.KObj(r))
+	h.cache.updateReservationIfExists(r)
```
Comment (KunWuLuan) [inline pkg/scheduler/plugins/reservation/eventhandler.go:94]: we can use`toReservation` in line 72-80

**Review by jasonliu747 — APPROVED** [review]
/lgtm

File: pkg/scheduler/plugins/reservation/eventhandler.go (hunk 1 above)
Comment (jasonliu747) [reply pkg/scheduler/plugins/reservation/eventhandler.go:94]: 你发誓，不然不给你过

Comment (jasonliu747) [reply pkg/scheduler/plugins/reservation/eventhandler.go:94]: image
