### PR TITLE
fix(OfferSlots):The number of OfferSlots should be adjusted according

### LINKED ISSUE #2739: [proposal] 网络拓扑领域计算某个拓扑领域支持的 OfferSlot 数量时感知一下 Step 做数量规整
**What is your proposal**:

当前我们网络拓扑算法计算一个 spine/leaf/node 可容纳的 Pod 数量是，是按照最小批次数量为 1 计算的。然后，有时候，我们希望一个 spine/leaf/node 可以容纳的 Pod 数量是 X 的整数倍，X 跟 spine/leaf/node 内通信参数有关，希望 Koordinator 可以支持该功能

**Why is this needed**:

**Is there a suggested solution, if so, please add it**:

### PR DESCRIPTION
**Pull request by AutuSnow**
### Ⅰ. Describe what this PR does
The number of OfferSlots should be adjusted according

### Ⅱ. Does this pull request fix one issue?

fixes #2739 

### V. Checklist

- [ ] I have written necessary docs and comments
- [ ] I have added necessary unit tests and integration tests
- [ ] All checks passed in `make test`

### CODE REVIEW

File: pkg/scheduler/plugins/coscheduling/core/network_topology_solver.go [hunk 1]
```diff
@@ -83,7 +84,21 @@ func (solver *networkTopologySolverImpl) PlacePods(
 	})
 
 	distribution := map[string]int{}
-	orderedNodes, _ := distributeOfferSlot(jobNetworkRequirements.DesiredOfferSlot, candidateTopologyNodes[0], distribution)
+	orderedNodes, actualOfferSlot := distributeOfferSlot(jobNetworkRequirements.DesiredOfferSlot, candidateTopologyNodes[0], distribution, jobNetworkRequirements.LayerSlotMultiple)
+
+	// Check if slot multiple constraint caused insufficient slots
+	if actualOfferSlot < jobNetworkRequirements.DesiredOfferSlot {
```
Comment (ZiMengSheng) [inline pkg/scheduler/plugins/coscheduling/core/network_topology_solver.go]: Why not perform this validation directly at L61? Taking Spine-Leaf topology as an example: validating at the current stage may cause the scheduler to select a Leaf node that fails to meet requirements, even though the Spine layer could satisfy them—such scenarios should not result in scheduling failure.

File: pkg/scheduler/plugins/coscheduling/core/network_topology_solver.go [hunk 2]
```diff
@@ -16,7 +16,8 @@ import (
 )
 
 const (
-	MessageNoCandidateTopologyNodes = "no candidate topology nodes can accommodate job, desiredOfferSlot: %d, %s, %s"
+	MessageNoCandidateTopologyNodes     = "no candidate topology nodes can accommodate job, desiredOfferSlot: %d, %s, %s"
```
Comment (ZiMengSheng) [inline pkg/scheduler/plugins/coscheduling/core/network_topology_solver.go]: Perhaps we don't need to introduce a new error type—simply appending details like slotMultiple constraints: %s to the existing error message would suffice.

File: apis/extension/coscheduling.go [hunk 3]
```diff
@@ -132,6 +132,14 @@ type NetworkTopologySpec struct {
...
 	Layer    schedulingv1alpha1.TopologyLayer `json:"layer"`
 	Strategy NetworkTopologyGatherStrategy    `json:"strategy"`
+	// SlotMultiple specifies that the number of Pods placed in this topology layer
+	// must be a multiple of this value. This is useful when the communication pattern
+	// within a topology layer requires a specific batch size.
+	// For example, if SlotMultiple is 8, the number of Pods in each spine/leaf/node
+	// will be 0, 8, 16, 24, etc.
+	// If not specified or set to 0/1, no multiple constraint is applied.
+	// +optional
+	SlotMultiple int `json:"slotMultiple,omitempty"`
```
Comment (ZiMengSheng) [inline apis/extension/coscheduling.go]: Let's rename it to PodCountMultiple—it looks more standard and aligns better with Kubernetes API naming conventions.

**Comment by AutuSnow** [comment]
@saintube Can you trigger 'retest' on this PR to see if the test bug can be replicated

**Comment by ZiMengSheng** [comment]
> @saintube Can you trigger 'retest' on this PR to see if the test bug can be replicated

I trigger by rebase main. Any push action will trigger it.

**Comment by AutuSnow** [comment]
> > @saintube Can you trigger 'retest' on this PR to see if the test bug can be replicated
> 
> I trigger by rebase main. Any push action will trigger it.

Running on his existing main branch, this problem occasionally occurs, and I feel that this phenomenon is becoming increasingly strange

File: pkg/scheduler/plugins/coscheduling/core/network_topology_solver.go
Comment (ZiMengSheng) [inline pkg/scheduler/plugins/coscheduling/core/network_topology_solver.go:64]: it should be constrainted here?
