### PR TITLE
[koord-runtime-proxy]: fix panic when no hook registered

### LINKED ISSUE #352: [BUG] koord-runtime-proxy report "invalid memory address or nil pointer dereference"
**What happened**:

After I deployed koordinator 0.5.0 and the koord-runtime-proxy, when I submit a pod with labels `koordinator.sh/enable-colocation: "true"`, the koord-runtime-proxy won't work and reported: 

```
Jul 08 15:01:25 xxx.xxx.xxx.xxx koord-runtime-proxy[195448]: I0708 15:01:25.128852  195448 pod.go:58] get pod info successful caa0e0e87a15124a051d517731ec0782e559f8659a9113a28a56411e2f3034c5
Jul 08 15:01:25 xxx.xxx.xxx.xxx koord-runtime-proxy[195448]: panic: runtime error: invalid memory address or nil pointer dereference
Jul 08 15:01:25 xxx.xxx.xxx.xxx koord-runtime-proxy[195448]: [signal SIGSEGV: segmentation violation code=0x1 addr=0xf8 pc=0x172b152]
Jul 08 15:01:25 xxx.xxx.xxx.xxx koord-runtime-proxy[195448]: goroutine 120 [running]:
Jul 08 15:01:25 xxx.xxx.xxx.xxx koord-runtime-proxy[195448]: github.com/koordinator-sh/koordinator/pkg/runtimeproxy/resexecutor/cri.(*PodResourceExecutor).UpdateRequest(0xc000b2a070, 0x0, 0x0, 0x1af6100, 0xc00066e8e8, 0x1bd0e37, 0x7)
Jul 08 15:01:25 xxx.xxx.xxx.xxx koord-runtime-proxy[195448]:         /root/projects/koordinator/pkg/runtimeproxy/resexecutor/cri/pod.go:132 +0x72
Jul 08 15:01:25 xxx.xxx.xxx.xxx koord-runtime-proxy[195448]: github.com/koordinator-sh/koordinator/pkg/runtimeproxy/server/cri.(*RuntimeManagerCriServer).interceptRuntimeRequest(0xc000a683c0, 0x1, 0x1e3e740, 0xc0007116e0, 0x1af6100, 0xc00066e8e8, 0xc0003b5b20, 0x0, 0x0, 0x0, ...)
Jul 08 15:01:25 xxx.xxx.xxx.xxx koord-runtime-proxy[195448]:         /root/projects/koordinator/pkg/runtimeproxy/server/cri/criserver.go:111 +0xa45
Jul 08 15:01:25 xxx.xxx.xxx.xxx koord-runtime-proxy[195448]: github.com/koordinator-sh/koordinator/pkg/runtimeproxy/server/cri.(*RuntimeManagerCriServer).StopPodSandbox(0xc000a683c0, 0x1e3e740, 0xc0007116e0, 0xc00066e8e8, 0xc000a683c0, 0xc0007116e0, 0xc000151ba0)
Jul 08 15:01:25 xxx.xxx.xxx.xxx koord-runtime-proxy[195448]:         /root/projects/koordinator/pkg/runtimeproxy/server/cri/runtime.go:41 +0x8e
Jul 08 15:01:25 xxx.xxx.xxx.xxx koord-runtime-proxy[195448]: k8s.io/cri-api/pkg/apis/runtime/v1alpha2._RuntimeService_StopPodSandbox_Handler(0x1b81b20, 0xc000a683c0, 0x1e3e740, 0xc0007116e0, 0xc00016aba0, 0x0, 0x1e3e740, 0xc0007116e0, 0xc000495bd0, 0x42)
Jul 08 15:01:25 xxx.xxx.xxx.xxx koord-runtime-proxy[195448]:         /root/go/pkg/mod/k8s.io/cri-api@v0.22.6/pkg/apis/runtime/v1alpha2/api.pb.go:8070 +0x217
Jul 08 15:01:25 xxx.xxx.xxx.xxx koord-runtime-proxy[195448]: google.golang.org/grpc.(*Server).processUnaryRPC(0xc000530540, 0x1e51858, 0xc000afe180, 0xc000b67e60, 0xc0006522a0, 0x29fd150, 0x0, 0x0, 0x0)
Jul 08 15:01:25 xxx.xxx.xxx.xxx koord-runtime-proxy[195448]:         /root/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:1286 +0x52b
Jul 08 15:01:25 xxx.xxx.xxx.xxx koord-runtime-proxy[195448]: google.golang.org/grpc.(*Server).handleStream(0xc000530540, 0x1e51858, 0xc000afe180, 0xc000b67e60, 0x0)
Jul 08 15:01:25 xxx.xxx.xxx.xxx koord-runtime-proxy[195448]:         /root/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:1609 +0xd0c
Jul 08 15:01:25 xxx.xxx.xxx.xxx koord-runtime-proxy[195448]: google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0001bb920, 0xc000530540, 0x1e51858, 0xc000afe180, 0xc000b67e60)
Jul 08 15:01:25 xxx.xxx.xxx.xxx koord-runtime-proxy[195448]:         /root/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:934 +0xab
Jul 08 15:01:25 xxx.xxx.xxx.xxx koord-runtime-proxy[195448]: created by google.golang.org/grpc.(*Server).serveStreams.func1
Jul 08 15:01:25 xxx.xxx.xxx.xxx koord-runtime-proxy[195448]:         /root/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:932 +0x1fd
```

The service file of koord-runtime-proxy is:

```
[Unit]
Description=Koordinator koord-runtime-proxy
Documentation=https://github.com/koordinator-sh/koordinator

[Service]
ExecStart=/usr/bin/koord-runtime-proxy  \
  --remote-runtime-service-endpoint=/var/run/containerd/containerd.sock \
  --remote-image-service-endpoint=/var/run/containerd/containerd.sock

Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
```

**What you expected to happen**:

koord-runtime-proxy works properly.

**How to reproduce it (as minimally and precisely as possible)**:

1. deploy koordinator following the doc: https://koordinator.sh/docs/installation
2. create a pod with label: `koordinator.sh/enable-colocation: "true"`

**Environment**: CentOS Linux release 8.2.2004 (Core)
- App version: 0.5.0
- Kubernetes version (use `kubectl version`):  1.21.0
- Install details (e.g. helm install args):
- Others:

### PR DESCRIPTION
**Pull request by cheimu**
### Ⅰ. Describe what this PR does
When no hook is registered, the dispatch will return a nil rsp, which will cause panic for UpdateRequest

### Ⅱ. Does this pull request fix one issue?
partly fixes #352 (the panic part)

### V. Checklist

- [ ] I have written necessary docs and comments
- [ ] I have added necessary unit tests and integration tests
- [ ] All checks passed in `make test`

### CODE REVIEW

File: pkg/runtimeproxy/server/cri/criserver.go [hunk 1]
```diff
@@ -105,7 +105,7 @@ func (c *RuntimeManagerCriServer) interceptRuntimeRequest(serviceType RuntimeSer
 
 	// pre call hook server
 	// TODO deal with the Dispatch response
-	if response, err := c.hookDispatcher.Dispatch(ctx, runtimeHookPath, config.PreHook, resourceExecutor.GenerateHookRequest()); err != nil {
+	if response, err := c.hookDispatcher.Dispatch(ctx, runtimeHookPath, config.PreHook, resourceExecutor.GenerateHookRequest()); err != nil || response == nil {
```
Comment (ZYecho) [inline pkg/runtimeproxy/server/cri/criserver.go:108]: no need to log error here in this case? WDYT？

Comment (cheimu) [reply pkg/runtimeproxy/server/cri/criserver.go:108]: @ZYecho I have no idea, @honpey WDYT？

Comment (jasonliu747) [reply pkg/runtimeproxy/server/cri/criserver.go:108]: I'm fine with either way.

```go
response, err := c.hookDispatcher.Dispatch(ctx, runtimeHookPath, config.PreHook, resourceExecutor.GenerateHookRequest())
if err != nil {
	// say something
}
if response == nil {
	// say something
}
err = resourceExecutor.UpdateRequest(response, request)
if err != nil {
	// say something
}
```

Comment (hormes) [reply pkg/runtimeproxy/server/cri/criserver.go:108]: yeah, add some comments about when the response is nil?

Comment (cheimu) [reply pkg/runtimeproxy/server/cri/criserver.go:108]: @hormes ok

Comment (cheimu) [reply pkg/runtimeproxy/server/cri/criserver.go]: Done @hormes @ZYecho @jasonliu747

**Review by jasonliu747 — COMMENTED** [review]
/lgtm
