### PR TITLE
koordlet: Reduce update NodeResourceTopology frequency

### LINKED ISSUE #817: [BUG] koordlet frequently Gets and Updates NodeResourceTopology
**What happened**:

The current nodeTopoInformer module of the koordlet Gets and Updates the NodeResourceTopology CR too frequently. It Gets the latest NodeResourceTopology every 3 seconds and Updates the CR even if it keeps unchanged. It causes unnecessary performance overhead and may affect the kube-apiserver when the number of nodes is large.

**What you expected to happen**:

Refactor the nodeTopoInformer module to reduce the overhead of reporting NodeResourceTopology. e.g. use the informer and cacheable update.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- App version: 1.0.0
- Kubernetes version (use `kubectl version`): 1.22
- Install details (e.g. helm install args):
- Node environment (for koordlet/runtime-proxy issue):
  - Containerd/Docker version:
  - OS version:
  - Kernal version:
  - Cgroup driver: cgroupfs/systemd
- Others:

### PR DESCRIPTION
**Pull request by Re-Grh**
Signed-off-by: Mew2 <1271013391@qq.com>

### Ⅰ. Describe what this PR does
Refactor the nodeTopoInformer module to reduce the overhead of reporting NodeResourceTopology.

### Ⅱ. Does this pull request fix one issue?
fixes #817 

### V. Checklist

- [ ] I have written necessary docs and comments
- [ ] I have added necessary unit tests and integration tests
- [ ] All checks passed in `make test`

### CODE REVIEW

File: pkg/koordlet/statesinformer/states_noderesourcetopology.go [hunk 1]
```diff
@@ -327,24 +327,41 @@ func (s *nodeTopoInformer) reportNodeTopology() {
...
 		klog.Errorf("failed to update NodeResourceTopology, err: %v", err)
 	}
 }
-
+func (s *nodeTopoInformer) isSyncNeeded(newAnnotations map[string]string) bool {
+	nodename := s.nodeInformer.GetNode().Name
+	if s.nodeTopology == nil {
+		return true
+	}
+	if util.IsequalTopo(s.nodeTopology.Annotations, newAnnotations) {
```
Comment (eahydra) [inline pkg/koordlet/statesinformer/states_noderesourcetopology.go:356]: Except that koordlet needs to check whether it is equal before reporting, is there any place where this function needs to be reused? If not, consider putting it near the reporting code first.

Comment (eahydra) [reply pkg/koordlet/statesinformer/states_noderesourcetopology.go:356]: In addition, should we also consider supporting Spec?

File: pkg/util/resource.go [hunk 2]
```diff
@@ -68,3 +68,22 @@ func IsResourceDiff(old, new corev1.ResourceList, resourceName corev1.ResourceNa
 
 	return newQuant >= oldQuant*(1+diffThreshold) || newQuant <= oldQuant*(1-diffThreshold)
 }
+
+// IsequalTopo returns whether the new topology has difference with the old one or not
+func IsequalTopo(oldtopo map[string]string, newtopo map[string]string) bool {
+	keySlice := make([]string, 0)
```
Comment (eahydra) [inline pkg/util/resource.go:74]: This check for equality may not be sufficient. For example, what is recorded in the annotation is a JSON object, but the serialization of the JSON object does not guarantee order (at this time, the JSON object data itself does not change.)

**Review by eahydra — COMMENTED** [review]
Please add some unit tests.

File: pkg/koordlet/statesinformer/states_noderesourcetopology.go [hunk 3]
```diff
@@ -327,24 +327,41 @@ func (s *nodeTopoInformer) reportNodeTopology() {
...
-			if err != nil {
-				klog.Errorf("failed to update cpu info of node %s, err: %v", node.Name, err)
-				return err
+		if s.isSyncNeeded(nodeResourceTopology.Annotations) {
+			// TODO only update if necessary
+			s.updateNodeTopo(nodeResourceTopology)
+
+			// do UPDATE
+			if features.DefaultKoordletFeatureGate.Enabled(features.NodeTopologyReport) {
+				_, err = s.topologyClient.TopologyV1alpha1().NodeResourceTopologies().Update(context.TODO(), nodeResourceTopology, metav1.UpdateOptions{})
```
Comment (saintube) [inline pkg/koordlet/statesinformer/states_noderesourcetopology.go:337]: Apart from the updating, how about using a NodeResourceTopology [informer](https://book-v1.book.kubebuilder.io/beyond_basics/using_client_go_informers.html) (please refer to the implementation of nodeMetricInformer module) to reduce the cost of getting since the nodeResourceTopology may change infrequently?

File: pkg/koordlet/statesinformer/states_noderesourcetopology.go [hunk 4]
```diff
@@ -327,24 +327,41 @@ func (s *nodeTopoInformer) reportNodeTopology() {
...
+			return nil
 		}
 		return nil
 	})
 	if err != nil {
 		klog.Errorf("failed to update NodeResourceTopology, err: %v", err)
 	}
 }
-
+func (s *nodeTopoInformer) isSyncNeeded(newAnnotations map[string]string) bool {
```
Comment (saintube) [inline pkg/koordlet/statesinformer/states_noderesourcetopology.go:351]: please leave a blank line before the function

File: pkg/koordlet/statesinformer/states_noderesourcetopology.go [hunk 5]
```diff
@@ -327,24 +327,41 @@ func (s *nodeTopoInformer) reportNodeTopology() {
...
-		// TODO only update if necessary
-		s.updateNodeTopo(nodeResourceTopology)
 
-		// do UPDATE
-		if features.DefaultKoordletFeatureGate.Enabled(features.NodeTopologyReport) {
-			_, err = s.topologyClient.TopologyV1alpha1().NodeResourceTopologies().Update(context.TODO(), nodeResourceTopology, metav1.UpdateOptions{})
-			if err != nil {
-				klog.Errorf("failed to update cpu info of node %s, err: %v", node.Name, err)
-				return err
+		if s.isSyncNeeded(nodeResourceTopology.Annotations) {
```
Comment (zwzhang0107) [inline pkg/koordlet/statesinformer/states_noderesourcetopology.go:331]: should check struct, not map of string

File: pkg/koordlet/statesinformer/states_noderesourcetopology.go (hunk 4 above)
Comment (zwzhang0107) [inline pkg/koordlet/statesinformer/states_noderesourcetopology.go:351]: need more ut

File: pkg/koordlet/statesinformer/states_noderesourcetopology.go [hunk 6]
```diff
@@ -327,24 +327,41 @@ func (s *nodeTopoInformer) reportNodeTopology() {
...
+	if util.IsequalTopo(s.nodeTopology.Annotations, newAnnotations) {
+		// do nothing
+		klog.Info("all good, no need to report nodetopo  %v", nodename)
+		return false
+	}
+	//not equal
+	klog.Warningf("node %v topology is changed, need sync", nodename)
+	return true
+}
 func (s *nodeTopoInformer) calCPUSharePools(sharedPoolCPUs map[int32]*extension.CPUInfo) []extension.CPUSharedPool {
```
Comment (jasonliu747) [inline pkg/koordlet/statesinformer/states_noderesourcetopology.go:365]: please leave a blank line between two functions

File: pkg/koordlet/statesinformer/states_noderesourcetopology.go [hunk 7]
```diff
@@ -327,24 +327,41 @@ func (s *nodeTopoInformer) reportNodeTopology() {
...
 }
-
+func (s *nodeTopoInformer) isSyncNeeded(newAnnotations map[string]string) bool {
+	nodename := s.nodeInformer.GetNode().Name
+	if s.nodeTopology == nil {
+		return true
+	}
+	if util.IsequalTopo(s.nodeTopology.Annotations, newAnnotations) {
+		// do nothing
+		klog.Info("all good, no need to report nodetopo  %v", nodename)
```
Comment (jasonliu747) [inline pkg/koordlet/statesinformer/states_noderesourcetopology.go:358]: please add a correct log level.

File: pkg/util/resource.go [hunk 8]
```diff
@@ -68,3 +68,22 @@ func IsResourceDiff(old, new corev1.ResourceList, resourceName corev1.ResourceNa
 
 	return newQuant >= oldQuant*(1+diffThreshold) || newQuant <= oldQuant*(1-diffThreshold)
 }
+
+// IsequalTopo returns whether the new topology has difference with the old one or not
+func IsequalTopo(oldtopo map[string]string, newtopo map[string]string) bool {
```
[the remark this answers is not in the document]
Comment (jasonliu747) [reply pkg/util/resource.go:73]: +1

File: pkg/koordlet/statesinformer/states_noderesourcetopology.go (hunk 3 above)
Comment (saintube) [reply pkg/koordlet/statesinformer/states_noderesourcetopology.go:338]: please add a TODO here: `TODO: use a NodeResourceTopology informer`

File: pkg/koordlet/statesinformer/states_noderesourcetopology.go [hunk 9]
```diff
@@ -345,6 +350,59 @@ func (s *nodeTopoInformer) reportNodeTopology() {
...
+	return true
+}
+
+// IsequalTopo returns whether the new topology has difference with the old one or not
+func isEqualTopo(oldtopo map[string]string, newtopo map[string]string) bool {
+	keySlice := make([]string, 0)
+	for key := range oldtopo {
+		keySlice = append(keySlice, key)
+	}
+	for _, key := range keySlice {
```
Comment (saintube) [inline pkg/koordlet/statesinformer/states_noderesourcetopology.go:373]: only compare the keys we can change

File: pkg/koordlet/statesinformer/states_noderesourcetopology.go [hunk 10]
```diff
@@ -345,6 +350,59 @@ func (s *nodeTopoInformer) reportNodeTopology() {
...
+		if _, ok := newtopo[key]; ok {
+			var (
+				old_data interface{}
+				new_data interface{}
+			)
+			if key == extension.AnnotationNodeCPUSharedPools {
+				old_data = make([]map[string]interface{}, 0)
```
Comment (saintube) [inline pkg/koordlet/statesinformer/states_noderesourcetopology.go:380]: is the slice type necessary?

File: pkg/koordlet/util/perf/perf_linux.go [hunk 11]
```diff
@@ -87,7 +87,7 @@ func GetContainerCyclesAndInstructions(collector *PerfCollector) (uint64, uint64
 	if err != nil {
 		return 0, 0, err
 	}
-	return result.instructions, result.cycles, nil
+	return result.cycles, result.instructions, nil
```
Comment (saintube) [inline pkg/koordlet/util/perf/perf_linux.go:90]: duplicated with #909

File: pkg/koordlet/statesinformer/states_noderesourcetopology.go [hunk 12]
```diff
@@ -345,6 +350,44 @@ func (s *nodeTopoInformer) reportNodeTopology() {
 	}
 }
 
+func isSyncNeeded(oldNRT, newNRT *v1alpha1.NodeResourceTopology, nodename string) bool {
+	if oldNRT == nil || oldNRT.Annotations == nil || newNRT.Annotations == nil {
+		return true
+	}
+	if isEqualTopo(oldNRT.Annotations, newNRT.Annotations) {
+		// do nothing
+		klog.V(4).Info("all good, no need to report nodetopo  %s", nodename)
```
Comment (saintube) [inline pkg/koordlet/statesinformer/states_noderesourcetopology.go:359]: use `klog.V().Infof()` for the print format, not `.Info()`. same below

**Review by saintube — APPROVED** [review]
/lgtm
