### PR TITLE
koord-scheduler: only remove unallocated ports if Reservation released

### LINKED ISSUE #1247: [BUG]Find an bug with resource reservation for hostport reservation.
**What happened**:
Find an bug with resource reservation for hostport reservation.
t0: reservation reserved hostport 8080 for pod-1.
t1: pod-1 used the reserved hostport 8080, and the nodeInfo recorded the occupation of hostport 8080.
t2: pod-1 successfully used the reservation, so reservation will immediately delete, causing the deletion of hostport 8080 of pod-1 from nodeInfo.
As a result, any new pod can now use hostport 8080 without any restrictions.
**What you expected to happen**:
Maybe it can add a used hostport in the reservation status, so that when deleting Reservepod, the used hostport can be set to nil.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- App version:
- Kubernetes version (use `kubectl version`):
- Install details (e.g. helm install args):
- Node environment (for koordlet/runtime-proxy issue):
  - Containerd/Docker version:
  - OS version:
  - Kernal version:
  - Cgroup driver: cgroupfs/systemd
- Others:

### PR DESCRIPTION
**Pull request by eahydra**
### Ⅰ. Describe what this PR does

fix #1247 : Reservation reserved ports that has been allocated by Pod but incorrectly removed from NdoeInfo if Reservation is deleted.   Now, just remove the unallocated ports in Reservation. 

### V. Checklist

- [x] I have written necessary docs and comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `make test`

### CODE REVIEW

**Comment by eahydra** [comment]
@fjding hi, I have resolved the issue, by the way, take a look?

**Comment by fjding** [comment]
> @fjding hi, I have resolved the issue, by the way, take a look?

👌🏻

File: pkg/scheduler/frameworkext/eventhandlers/reservation_handler.go [hunk 1]
```diff
@@ -327,43 +326,59 @@ func updateReservationInCache(sched frameworkext.Scheduler, oldObj, newObj inter
...
+	rInfo := reservationCache.DeleteReservation(r)
+	if rInfo == nil {
+		klog.Warningf("The impossible happened. Missing ReservationInfo in ReservationCache, reservation: %v", klog.KObj(r))
+		return
+	}
+
 	reservePod := reservationutil.NewReservePod(r)
-	if err := sched.GetCache().RemovePod(reservePod); err != nil {
-		klog.Errorf("scheduler cache RemovePod failed for reservation, reservation %s, err: %v", klog.KObj(r), err)
+	if _, err = sched.GetCache().GetPod(reservePod); err == nil {
```
Comment (fjding) [inline pkg/scheduler/frameworkext/eventhandlers/reservation_handler.go:359]: existPod, err = sched.GetCache().GetPod(reservePod)
here may remove the usedports on the existPod  in the cache. not the reservePod.
because in  RemovePod method , it use the pod which in the cache
image

Comment (eahydra) [reply pkg/scheduler/frameworkext/eventhandlers/reservation_handler.go:359]: Yes.. So before remove, must update the pod first..

**Comment by eahydra** [comment]
/hold cancel

TBR @hormes @FillZpp @ZiMengSheng @fjding

**Comment by eahydra** [comment]
All E2E passed.

File: pkg/scheduler/frameworkext/reservation_info.go [hunk 2]
```diff
@@ -25,38 +25,67 @@ import (
...
+	return &PodRequirement{
+		Namespace: pod.Namespace,
+		Name:      pod.Name,
+		UID:       pod.UID,
+		Requests:  requests,
+		Ports:     ports,
+	}
+}
+
+func (p *PodRequirement) Clone() *PodRequirement {
```
Comment (FillZpp) [inline pkg/scheduler/frameworkext/reservation_info.go:67]: DeepCopy?

**Review by jasonliu747 — APPROVED** [review]
/lgtm
