### PR TITLE
fix: consider lse/lsr when cpu suppress (#234)

### LINKED ISSUE #234: [proposal] cpu suppress policy should take fine-grined cpu orchestration into consideration
**What is your proposal**:
`cpu suppress` policy change the cpuset of BE pod dynamically. fine-grined cpu orchestration rule should be considers. see https://github.com/koordinator-sh/koordinator/issues/96 for more details.

**Why is this needed**:
BE pod should not share CPU with LSE.
fairness of the BE cpuset should be considered, in case the BE cpuset are shared to only few LSR/LS pods. 

**Is there a suggested solution, if so, please add it**:
take the cpu core number into account during the share of cpuset between BE and LSR/LS.
1. calculate the target number of suppressed cpu.
2. each LSR/LS contribute some cpu to share with BE by their request proportion.
3. apply cpuset for BE pods

### PR DESCRIPTION
**Pull request by ZYecho**
Signed-off-by: Yue Zhang <huaihuan.zy@alibaba-inc.com>

### Ⅰ. Describe what this PR does
fix #234 

### V. Checklist

- [ ] I have written necessary docs and comments
- [ ] I have added necessary unit tests and integration tests
- [ ] All checks passed in `make test`

### CODE REVIEW

File: pkg/koordlet/resmanager/cpu_suppress.go [hunk 1]
```diff
@@ -158,16 +159,9 @@ func (r *CPUSuppress) calculateBESuppressCPU(node *corev1.Node, nodeMetric *metr
...
 
 // calculateBESuppressPolicy calculates the be cpu suppress policy with cpuset cpus number and node cpu info
-func calculateBESuppressCPUSetPolicy(cpusetQuantity *resource.Quantity, oldCPUSetNum int, nodeCPUInfo *metriccache.NodeCPUInfo) []int32 {
-	// set the number of cpuset cpus no less than 2
-	cpus := int32(math.Ceil(float64(cpusetQuantity.MilliValue()) / 1000))
-	if cpus < 2 {
-		cpus = 2
-	}
-
+func calculateBESuppressCPUSetPolicy(cpus int32, oldCPUSetNum int, processorInfos []util.ProcessorInfo) []int32 {
```
Comment (zwzhang0107) [inline pkg/koordlet/resmanager/cpu_suppress.go:162]: split the processors into several partitions(socket+node), try to get 1 core(2 processors) from each partition for each iteration

**Comment by zwzhang0107** [comment]
recoverCPUSetIfNeed needs to reset as be-share-pool(node-lse)

**Review by zwzhang0107 — COMMENTED** [review]
recoverCPUSetIfNeed need to reset cpu as be-share-pool(node-LSE)

File: pkg/koordlet/resmanager/cpu_suppress.go [hunk 2]
```diff
@@ -182,29 +176,37 @@ func calculateBESuppressCPUSetPolicy(cpusetQuantity *resource.Quantity, oldCPUSe
...
+		nodeIndex := getNodeIndex(processor)
+		if _, ok := coreIdSetofNode[nodeIndex]; !ok {
+			coreIdSetofNode[nodeIndex] = map[int32]int32{}
 		}
+		coreIdSetofNode[nodeIndex][processor.CoreID]++
 	}
 
-	// first we prefer the scattered node/socket, secondly the same core
+	for _, processor := range prioritizedCPUs {
+		coreIndexOfNode[processor.CoreID] = int32(len(coreIdSetofNode[getNodeIndex(processor)]))
```
Comment (eahydra) [inline pkg/koordlet/resmanager/cpu_suppress.go:202]: In the past, I have encountered a special machine with the same Core ID under different Sockets. Should not directly take the CoreID to participate in the calculation.

File: pkg/koordlet/resmanager/cpu_suppress.go [hunk 3]
```diff
@@ -182,29 +176,37 @@ func calculateBESuppressCPUSetPolicy(cpusetQuantity *resource.Quantity, oldCPUSe
...
-	indexOfNode := map[int32]int32{}
-	numProcessorsOfNode := map[int32]int32{}
+	coreIndexOfNode := map[int32]int32{}
+	coreIdSetofNode := map[int32]map[int32]int32{}
 	for _, processor := range prioritizedCPUs {
-		numProcessorsOfNode[getNodeIndex(processor)]++
-		if indexOfNode[processor.CoreID] <= 0 {
-			indexOfNode[processor.CoreID] = numProcessorsOfNode[getNodeIndex(processor)]
+		nodeIndex := getNodeIndex(processor)
+		if _, ok := coreIdSetofNode[nodeIndex]; !ok {
```
Comment (saintube) [inline pkg/koordlet/resmanager/cpu_suppress.go:195]: `coreIdSetofNode` may be incorrect when two CPUs are on different Sockets but have the same Core ID.

File: pkg/koordlet/resmanager/cpu_suppress.go (hunk 2 above)
Comment (eahydra) [reply pkg/koordlet/resmanager/cpu_suppress.go:202]: @hormes reminded that the data of `lscpu -e` and `/proc/cpuinfo` are inconsistent. After investigation and analysis, the problems I encountered in the past should be caused by the internal version not processing the data of cadvisor correctly. Taking the X86 architecture as an example, the so-called `CoreID` we see through `lscpu -e` is actually the minimum ID among the two logical cores under the same physical core. For example, Core A has two logical cores 26 and 80, then the CoreID is 26.

File: pkg/koordlet/resmanager/cpu_suppress.go [hunk 4]
```diff
@@ -341,20 +332,68 @@ func (r *CPUSuppress) suppressBECPU() {
...
+				continue
+			}
+			for _, cpuID := range set.ToSliceNoSort() {
+				cpuIdToPool[int32(cpuID)] = apiext.GetPodQoSClass(podMeta.Pod)
+			}
+		}
+	}
+	lsrCpus := []util.ProcessorInfo{}
+	lsCpus := []util.ProcessorInfo{}
+	for _, processor := range nodeCPUInfo.ProcessorInfos {
```
Comment (zwzhang0107) [inline pkg/koordlet/resmanager/cpu_suppress.go:369]: please add a FIXME comments here: "be pods might be starved since lse pods can run out of all cpus"

File: pkg/koordlet/resmanager/cpu_suppress.go [hunk 5]
```diff
@@ -158,95 +159,85 @@ func (r *CPUSuppress) calculateBESuppressCPU(node *corev1.Node, nodeMetric *metr
...
+			}
+			if cpuBucket[bucketIndex][i].CoreID == cpuBucket[bucketIndex][i+1].CoreID {
+				selectdIndex = i
+				break
+			}
 		}
-		CPUSets = append(CPUSets, prioritizedCPUs[i].CPUID)
-		needCPUs--
+		CPUSets = append(CPUSets, cpuBucket[bucketIndex][selectdIndex].CPUID, cpuBucket[bucketIndex][selectdIndex+1].CPUID)
+		cpuBucket[bucketIndex][selectdIndex].CPUID = -1
```
Comment (zwzhang0107) [inline pkg/koordlet/resmanager/cpu_suppress.go:237]: mark "-1" to cpu id seems tricky, consider using a bitmap to record allocation result

File: pkg/koordlet/resmanager/cpu_suppress.go [hunk 6]
```diff
@@ -158,95 +159,85 @@ func (r *CPUSuppress) calculateBESuppressCPU(node *corev1.Node, nodeMetric *metr
...
+			}
+			CPUSets = append(CPUSets, cpuBucket[bucketIndex][selectdIndex].CPUID)
+			cpuBucket[bucketIndex][selectdIndex].CPUID = -1
+			needCPUs--
+			bucketIndex = (bucketIndex + 1) % len(cpuBucket)
+			continue
+		}
+		// prefer the same core
+		selectdIndex := 0
+		for i := 0; i < len(cpuBucket[bucketIndex])-1; i++ {
```
Comment (zwzhang0107) [inline pkg/koordlet/resmanager/cpu_suppress.go:227]: one bucket might runs out early, cpu[0-1] will be reallocated

File: pkg/util/system/util_test_tool.go [hunk 7]
```diff
@@ -36,7 +36,7 @@ type FileTestUtil struct {
 func NewFileTestUtil(t *testing.T) *FileTestUtil {
 	// NOTE: When $TMPDIR is not set, `t.TempDir()` can use different base directory on Mac OS X and Linux, which may
 	// generates too long paths to test unix socket.
-	t.Setenv("TMPDIR", "/tmp")
+	// t.Setenv("TMPDIR", "/tmp")
```
Comment (saintube) [inline pkg/util/system/util_test_tool.go:39]: why comment this line?

File: pkg/koordlet/resmanager/cpu_suppress.go [hunk 8]
```diff
@@ -158,95 +159,85 @@ func (r *CPUSuppress) calculateBESuppressCPU(node *corev1.Node, nodeMetric *metr
...
-		return a.CPUID > b.CPUID
+		return len(cpuBucket[i]) > len(cpuBucket[j])
 	})
 
 	needCPUs := cpus
-	for i := range prioritizedCPUs {
-		if needCPUs <= 0 {
-			break
+	bucketIndex := 0
+	for needCPUs > 0 {
```
Comment (zwzhang0107) [inline pkg/koordlet/resmanager/cpu_suppress.go:206]: add a protection in case of looping forever

File: pkg/koordlet/resmanager/cpu_suppress.go [hunk 9]
```diff
@@ -158,95 +159,85 @@ func (r *CPUSuppress) calculateBESuppressCPU(node *corev1.Node, nodeMetric *metr
...
+		if needCPUs == 1 || len(cpuBucket[bucketIndex]) == 1 {
+			// prefer the single core cpu id
+			selectdIndex := 0
+			for i := 0; i < len(cpuBucket[bucketIndex]); i++ {
+				if cpuBucket[bucketIndex][i].CPUID < 0 {
+					continue
+				}
+				if (i == 0 || cpuBucket[bucketIndex][i].CoreID != cpuBucket[bucketIndex][i-1].CoreID) && (i+1 == len(cpuBucket[bucketIndex]) || cpuBucket[bucketIndex][i].CoreID != cpuBucket[bucketIndex][i+1].CoreID) {
```
Comment (zwzhang0107) [inline pkg/koordlet/resmanager/cpu_suppress.go:214]: this condition seems too complex, consider set the allocation into two stages: 1. allocate cpu pair of same physical core. 2. allocate from other independent cpu-HT.

File: pkg/koordlet/resmanager/cpu_suppress.go [hunk 10]
```diff
@@ -158,95 +159,85 @@ func (r *CPUSuppress) calculateBESuppressCPU(node *corev1.Node, nodeMetric *metr
...
-
 	// getNodeIndex is a function to calculate an index for every numa node or socket
 	getNodeIndex := func(info util.ProcessorInfo) int32 {
+		// (nodeId, socketId) => nodeIndex
 		return (info.NodeID + numProcessors) * (info.SocketID + 1)
 	}
+	cpuBucketOfNode := map[int32][]util.ProcessorInfo{}
+	for _, p := range processorInfos {
+		nodeIndex := getNodeIndex(p)
+		cpuBucketOfNode[nodeIndex] = append(cpuBucketOfNode[nodeIndex], p)
```
[the remark this answers is not in the document]
Comment (ZYecho) [reply pkg/koordlet/resmanager/cpu_suppress.go:179]: append(nil, p) will work

File: pkg/koordlet/resmanager/cpu_suppress.go [hunk 11]
```diff
@@ -158,98 +159,102 @@ func (r *CPUSuppress) calculateBESuppressCPU(node *corev1.Node, nodeMetric *metr
...
-	for i := range prioritizedCPUs {
+	usedCpu := map[int32]bool{}
+	// select same core cpu id
+	preNeedCpus := int32(-1)
+	i := 0
+	for ; i < len(cpuBucket); i = (i + 1) % len(cpuBucket) {
+		if needCPUs <= 1 {
+			break
+		}
+		if i == len(cpuBucket) {
```
Comment (zwzhang0107) [inline pkg/koordlet/resmanager/cpu_suppress.go:213]: this never happens due to `(i + 1) % len(cpuBucket)`
consider check then current and pre length of usedCpu

File: pkg/koordlet/resmanager/cpu_suppress.go [hunk 12]
```diff
@@ -158,98 +159,102 @@ func (r *CPUSuppress) calculateBESuppressCPU(node *corev1.Node, nodeMetric *metr
...
+			usedCpu[cpuBucket[i][selectdIndex+1].CPUID] = true
+			needCPUs = needCPUs - 2
+		}
+	}
+
+	// select single cpu id
+	for ; i < len(cpuBucket); i = (i + 1) % len(cpuBucket) {
 		if needCPUs <= 0 {
 			break
 		}
```
Comment (zwzhang0107) [inline pkg/koordlet/resmanager/cpu_suppress.go:242]: add a protection break by checking current and pre length of usedCpu

File: pkg/koordlet/resmanager/cpu_suppress.go [hunk 13]
```diff
@@ -158,98 +159,111 @@ func (r *CPUSuppress) calculateBESuppressCPU(node *corev1.Node, nodeMetric *metr
...
-	// it will get sorted as below:
-	//	CPUID	CoreID	SocketID	NodeID
-	//	7		3		1			1
-	//	3		3		1			1
-	//	5		1		0			0
-	//	1		1		0			0
-	//	6		2		1			1
-	//	2		2		1			1
-	//	4		0		0			0
-	//	0		0		0			0
```
Comment (jasonliu747) [inline pkg/koordlet/resmanager/cpu_suppress.go:228]: can you keep this kind of figure in comment, so ppl could understand what we're trying to do more easily.
