### PR TITLE
koord-scheduler: fix Coscheduling resource deadlock with groups

### LINKED ISSUE #872: [BUG]deadlock when schedule multi-gang-group
**What happened**:
if there are pod group A,B,C,D in the cluster, A and B are a group while C and D are a group.
if the pod groups are scheduled in the following order: A C B D, a deadlock may happen when pod group A and C occupy all resource is the cluster.
**What you expected to happen**:
when pod group B find that the resource is not enough, it can reject pod group A so that pod group C and D can bind.
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- App version:
- Kubernetes version (use `kubectl version`):
- Install details (e.g. helm install args):
- Node environment (for koordlet/runtime-proxy issue):
  - Containerd/Docker version:
  - OS version:
  - Kernal version:
  - Cgroup driver: cgroupfs/systemd
- Others:

### PR DESCRIPTION
**Pull request by KunWuLuan**
### Ⅰ. Describe what this PR does
fix: deadlock when schedule multi-gang-group

### Ⅱ. Does this pull request fix one issue?
fixes #872

### V. Checklist

- [ ] I have written necessary docs and comments
- [ ] I have added necessary unit tests and integration tests
- [ ] All checks passed in `make test`

### CODE REVIEW

File: pkg/scheduler/plugins/coscheduling/core/core.go [hunk 1]
```diff
@@ -62,12 +63,14 @@ type Manager interface {
 	PostBind(context.Context, *corev1.Pod, string)
 	PostFilter(context.Context, *corev1.Pod, framework.Handle, string) (*framework.PostFilterResult, *framework.Status)
 	GetCreatTime(*framework.QueuedPodInfo) time.Time
+	GetGroupId(*corev1.Pod) ([]byte, error)
```
Comment (eahydra) [inline pkg/scheduler/plugins/coscheduling/core/core.go:66]: it's better to return string instead of byte slice.

File: pkg/scheduler/plugins/coscheduling/core/gang.go [hunk 2]
```diff
@@ -50,6 +53,7 @@ type Gang struct {
 	Mode              string
 	MinRequiredNumber int
 	TotalChildrenNum  int
+	GangGroupId       []byte
```
Comment (eahydra) [inline pkg/scheduler/plugins/coscheduling/core/gang.go:56]: use `string` instead of `[]byte`

File: pkg/scheduler/plugins/coscheduling/core/gang_cache_test.go [hunk 3]
```diff
@@ -484,6 +487,15 @@ func TestGangCache_OnPodAdd(t *testing.T) {
...
 				gangCache.onPodAdd(pod)
 			}
+			for k, v := range tt.wantCache {
+				if !v.HasGangInit {
+					continue
+				}
+				sort.Strings(v.GangGroup)
+				s := strings.Join(v.GangGroup, ",")
+				encoded := md5.Sum([]byte(s))
+				tt.wantCache[k].GangGroupId = encoded[:]
```
Comment (eahydra) [inline pkg/scheduler/plugins/coscheduling/core/gang_cache_test.go:497]: these code are duplicated in gang.go.

File: pkg/scheduler/plugins/coscheduling/core/gang_cache_test.go [hunk 4]
```diff
@@ -669,6 +681,15 @@ func TestGangCache_OnPodDelete(t *testing.T) {
...
 				gangCache.onPodDelete(pod)
 			}
+			for k, v := range tt.wantCache {
+				if !v.HasGangInit {
+					continue
+				}
+				sort.Strings(v.GangGroup)
+				s := strings.Join(v.GangGroup, ",")
+				encoded := md5.Sum([]byte(s))
+				tt.wantCache[k].GangGroupId = encoded[:]
```
Comment (eahydra) [inline pkg/scheduler/plugins/coscheduling/core/gang_cache_test.go:691]: same problem here

File: pkg/scheduler/plugins/coscheduling/core/gang_cache_test.go [hunk 5]
```diff
@@ -815,6 +836,15 @@ func TestGangCache_OnPodGroupAdd(t *testing.T) {
...
 				gangCache.onPodGroupAdd(pg)
 			}
+			for k, v := range tt.wantCache {
+				if !v.HasGangInit {
+					continue
+				}
+				sort.Strings(v.GangGroup)
+				s := strings.Join(v.GangGroup, ",")
+				encoded := md5.Sum([]byte(s))
+				tt.wantCache[k].GangGroupId = encoded[:]
```
Comment (eahydra) [inline pkg/scheduler/plugins/coscheduling/core/gang_cache_test.go:846]: same problem here

File: pkg/scheduler/plugins/coscheduling/core/gang_cache_test.go [hunk 6]
```diff
@@ -931,6 +961,10 @@ func TestGangCache_OnGangDelete(t *testing.T) {
 		ChildrenScheduleRoundMap: map[string]int{},
 	}
 	cacheGang := cache.getGangFromCacheByGangId("default/gangb", false)
+	sort.Strings(wantedGang.GangGroup)
+	s := strings.Join(wantedGang.GangGroup, ",")
+	encoded := md5.Sum([]byte(s))
+	wantedGang.GangGroupId = encoded[:]
```
Comment (eahydra) [inline pkg/scheduler/plugins/coscheduling/core/gang_cache_test.go:967]: same problem here

**Review by eahydra — CHANGES_REQUESTED** [review]

**Review by eahydra — COMMENTED** [review]
/lgtm

**Review by jasonliu747 — COMMENTED** [review]
@KunWuLuan Hi, thanks for your hard work. Please fix the CI, and we're all set.

**Review by eahydra — COMMENTED** [review]
/lgtm

File: pkg/scheduler/plugins/coscheduling/core/core.go [hunk 7]
```diff
@@ -311,16 +328,40 @@ func (pgMgr *PodGroupManager) Unreserve(ctx context.Context, state *framework.Cy
 	gang.delAssumedPod(pod)
 
 	if !gang.isGangOnceResourceSatisfied() && gang.getGangMode() == extension.GangModeStrict {
-		// release resource of all assumed children of the gang
+		pgMgr.rejectGangGroupById(gang.Name, handle)
+	}
+}
+
+func (pgMgr *PodGroupManager) rejectGangGroupById(gangId string, handle framework.Handle) {
```
Comment (xulinfei1996) [inline pkg/scheduler/plugins/coscheduling/core/core.go:335]: Maybe can add pluginName string as input, print waitingPod.Reject(pluginName,"gang rejection by another ganggroup").
Or modify the interface Manager's functions Unreserve、PostFilter.

Comment (eahydra) [reply pkg/scheduler/plugins/coscheduling/core/core.go:335]: The pgMgr.PostFilter method already has a pluginName parameter. Can use this directly.

File: pkg/scheduler/plugins/coscheduling/core/gang.go [hunk 8]
```diff
@@ -151,7 +152,7 @@ func (gang *Gang) tryInitByPodConfig(pod *v1.Pod, args *config.CoschedulingArgs)
 			gang.Name, pod.Annotations[extension.AnnotationGangGroups])
 	}
 	gang.GangGroup = groupSlice
-
+	gang.GangGroupId = util.GetGangGroupId(groupSlice)
```
Comment (eahydra) [inline pkg/scheduler/plugins/coscheduling/core/gang.go:155]: An optimization can be considered here to ensure that the groupSlice contains at least one member and prevent the group id from being empty.

File: pkg/scheduler/plugins/coscheduling/core/core.go (hunk 7 above)
Comment (KunWuLuan) [reply pkg/scheduler/plugins/coscheduling/core/core.go:335]: good idea, thanks

File: pkg/scheduler/plugins/coscheduling/core/gang.go (hunk 8 above)
Comment (KunWuLuan) [reply pkg/scheduler/plugins/coscheduling/core/gang.go:155]: You mean the groupId is a pointer to string?

**Review by eahydra — APPROVED** [review]
/lgtm
/approve
